Feat/frontend/contest top
szpp-dev-team/szpp-judge pull request #108
Opened 2023-10-07 08:57 UTC by piddy-shz

コンテストトップページの実装です
理由はわかりませんが非ログイン状態の場合にタイマーが動かないっぽいので、ログインしてないとタイマー表示しないようにしました
多分まだ他にも粗があると思います

2023-10-07 14:22 UTC, h-takeyeah reviewed
PR お疲れ様です！とりあえずタイマーが動かない原因はコメントしました．

条件(`contest` が undefined でない云々)によって expireTimestamp を変更しないといけないという仕様が問題を難しくしていますね．調査します．

2023-10-07 14:22 UTC, h-takeyeah commented on frontend/src/components/page/ContestTop/ContestTop.tsx
> +  const timer = useTimer({ expiryTimestamp });
初回のレンダーでは必ず25行目の else 節に入ります．なぜなら `contest` が undefined だからです．そしてそのまま expirtyTimestamp が now (つまり expire まで 0)の状態で `useTimer` が呼び出されます．
それで呼び出された `useTimer` はその後たとえ `contest` が undefined でなくなっても初回の呼び出しを使い続けます．なので16行目からの if 文が無視されている状態になっています．

2023-10-07 14:44 UTC, h-takeyeah commented on frontend/src/components/page/ContestTop/ContestTop.tsx
> +  const timer = useTimer({ expiryTimestamp });
条件付きで useXXX を呼び出したり呼び出さなかったりするのは React のお作法的にできません．かといって `contest` に依存している `isUpcomingOrRunning` や `timerHeader` を全て useState に入れるのも違う感じがします．(レンダー間をまたいで保持が必要な情報ではないしリアクティブである必要もないので)

コンポーネントを分けるのがベストかと思われます．

2023-10-08 04:26 UTC, piddy-shz commented on frontend/src/components/page/ContestTop/ContestTop.tsx
> +  const timer = useTimer({ expiryTimestamp });
ありがとうございます。修正しました

2023-10-08 05:19 UTC, h-takeyeah requested changes
`contest?.startAt != undefined` の部分ですが，`!=` を `!==` に変更するか，単に `contest?.startAt` に変更してもらいたいです(提案)．
右辺が undefined の場合はそこまで気にしなくていい話なのですが，`!=`(不等価)と`!==`(厳密不等価)は挙動が違うので後者の方が動作が予測しやすいためです．逆に `!=` でいい場合は undefined と比較する(`左辺の式 != undefined`)なら単に `左辺の式` でもほぼ同じです．

2023-10-08 05:19 UTC, h-takeyeah commented on frontend/src/components/page/ContestTop/ContestTop.tsx
> +  let seq = [
let の必要はないので const に修正お願いします:bow:
```suggestion
  const seq = [
```

配列の要素の変更は変数への再代入ではないので const でも動きます

2023-10-08 05:25 UTC, piddy-shz commented on frontend/src/components/page/ContestTop/ContestTop.tsx
> +  let seq = [
これ知りませんでした......直します

2023-10-08 05:35 UTC, h-takeyeah requested changes

2023-10-08 05:35 UTC, h-takeyeah commented on frontend/src/components/page/ContestTop/ContestTop.tsx
> +  </div>
超細かいのですが，修正お願いします:bow:

```suggestion
  return <span>
    {props.timerHeader + seq[0] + ":" + seq[1] + ":" + seq[2] + ":" + seq[3]}
  </span>
```
ContestTop 側が `<p>` の中で TimerComponent を呼び出しているので `<div>` だと `<p><div></div></p>` になって HTML として正しくないので div 以外のタグに変更をお願いします．

![image](https://github.com/szpp-dev-team/szpp-judge/assets/61489178/25221af1-19d7-4d49-b5bd-19eb1ff64117)

2023-10-08 05:49 UTC, piddy-shz commented on frontend/src/components/page/ContestTop/ContestTop.tsx
> +  </div>
span タグに変更しました

2023-10-08 06:11 UTC, h-takeyeah approved these changes

2023-10-08 07:53 UTC, merged